# Imagen base
FROM node:22.13.1

# Crea un directorio llamado "app" en la ruta /usr/src/ con la opción -p para asegurar que se crean todo>
RUN mkdir -p /usr/src/app

# Establece la ruta de trabajo para las siguientes instrucciones
WORKDIR /usr/src/app

# Copia los archivos que coincidan con el patrón package*.json desde el sistema de archivos del host has>
COPY package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

# Copia todos los archivos y carpetas del directorio actual en el sistema de archivos del host donde se >
COPY . .

# Indica que el contenedor escuchará en el puerto 8082
EXPOSE 8082

# Especifica el comando por defecto para ejecutar al iniciar el contenedor
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "8082"]
